# Tasks Discussion

## Model Import and Evaluation

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix 

In [57]:
# Importing our own model

import joblib

model = joblib.load("../models/model.joblib")
model

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('tfidfvectorizer', ...), ('multinomialnb', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[<U13](5,)","['business','entertainment','politics','sport','tech']"
,"stop_words stop_words: {'english'}, list, default=NoneIf a string, it is passed to _check_stop_list and the appropriate stoplist is returned. 'english' is currently the only supported stringvalue.There are several known issues with 'english' and you shouldconsider an alternative (see :ref:`stop_words`).If a list, that list is assumed to contain stop words, all of whichwill be removed from the resulting tokens.Only applies if ``analyzer == 'word'``.If None, no stop words will be used. In this case, setting `max_df`to a higher value, such as in the range (0.7, 1.0), can automatically detectand filter stop words based on intra corpus document frequency of terms.",'english'
,"input input: {'filename', 'file', 'content'}, default='content'- If `'filename'`, the sequence passed as an argument to fit is expected to be a list of filenames that need reading to fetch the raw content to analyze.- If `'file'`, the sequence items must have a 'read' method (file-like object) that is called to fetch the bytes in memory.- If `'content'`, the input is expected to be a sequence of items that can be of type string or byte.",'content'
,"encoding encoding: str, default='utf-8'If bytes or files are given to analyze, this encoding is used todecode.",'utf-8'
,"decode_error decode_error: {'strict', 'ignore', 'replace'}, default='strict'Instruction on what to do if a byte sequence is given to analyze thatcontains characters not of the given `encoding`. By default, it is'strict', meaning that a UnicodeDecodeError will be raised. Othervalues are 'ignore' and 'replace'.",'strict'
,"strip_accents strip_accents: {'ascii', 'unicode'} or callable, default=NoneRemove accents and perform other character normalizationduring the preprocessing step.'ascii' is a fast method that only works on characters that havea direct ASCII mapping.'unicode' is a slightly slower method that works on any characters.

In [58]:
df = pd.read_csv("../bbc_news_dataset.csv")

new_df = df.copy()

X = df["Text"]
y = df["Category"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [59]:
y_train

305          business
783              tech
197             sport
941     entertainment
977              tech
            ...      
145          politics
440              tech
1366         business
68               tech
705          business
Name: Category, Length: 1192, dtype: str

In [60]:
y_test

1439             tech
815     entertainment
1403            sport
1360         politics
846          politics
            ...      
6               sport
954     entertainment
1105             tech
964     entertainment
308     entertainment
Name: Category, Length: 298, dtype: str

In [61]:
X_test

1439    what high-definition will do to dvds first it ...
815     stars pay tribute to actor davis hollywood sta...
1403    roche  turns down federer offer  australian te...
1360    ukip candidate suspended eurosceptic party uki...
846     brown and blair face new rift claims for the u...
                              ...                        
6       wales silent on grand slam talk rhys williams ...
954     oscar host rock to keep it clean oscar host ch...
1105    tough rules for ringtone sellers firms that fl...
964     volcano drama erupts on bbc one supervolcano  ...
308     new york rockers top talent poll new york elec...
Name: Text, Length: 298, dtype: str

In [62]:
X_train

305     winter freeze keeps oil above $50 oil prices c...
783     concerns over windows atms cash machine networ...
197     holmes is hit by hamstring injury kelly holmes...
941     wal-mart is sued over rude lyrics the parents ...
977     nintendo adds media playing to ds nintendo is ...
                              ...                        
145     uk  needs true immigration data  a former home...
440     honour for uk games maker leading british comp...
1366    business fears over sluggish eu economy as eur...
68      us state acts to stop  spammers  us state texa...
705     air china in $1bn london listing china s natio...
Name: Text, Length: 1192, dtype: str

In [63]:
# Evaluating the model accuracy , precision , recall  , and f1-score .

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [64]:
y_pred = model.predict(X_test)
y_pred

array(['tech', 'entertainment', 'sport', 'politics', 'politics', 'tech',
       'entertainment', 'business', 'entertainment', 'entertainment',
       'business', 'politics', 'politics', 'sport', 'entertainment',
       'business', 'business', 'entertainment', 'business',
       'entertainment', 'tech', 'sport', 'tech', 'politics', 'tech',
       'sport', 'sport', 'entertainment', 'politics', 'entertainment',
       'business', 'entertainment', 'business', 'politics', 'tech',
       'business', 'politics', 'politics', 'sport', 'entertainment',
       'business', 'tech', 'sport', 'sport', 'business', 'tech', 'sport',
       'entertainment', 'tech', 'business', 'sport', 'entertainment',
       'sport', 'politics', 'tech', 'politics', 'business', 'politics',
       'business', 'sport', 'business', 'politics', 'sport', 'tech',
       'sport', 'tech', 'entertainment', 'politics', 'entertainment',
       'politics', 'entertainment', 'business', 'sport', 'tech', 'sport',
       'politics', 'po

In [65]:
# Since this is a multiclass classification problem, precision, recall,
# and F1-score are first calculated for each class individually.
# The 'average' parameter specifies how these per-class scores are
# combined into a single overall metric.
# Here, 'weighted' computes the weighted average using the support
# (number of true samples) of each class.


precision = precision_score(y_test, y_pred, average="weighted")
f1 = f1_score(y_test, y_pred, average="weighted")
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred, average="weighted")


print(
    f"The accuracy is {accuracy} \nThe precision is {precision} \nThe recall is {recall} \nThe f1-score is {f1}\n"
)
# in percentage
print("In Percentage : \n")
print(
    f"The accuracy is {accuracy*100:.2f} % \nThe precision is {precision*100:.2f} % \nThe recall is {recall*100:.2f} % \nThe f1-score is {f1*100:.2f} %"
)

The accuracy is 0.9899328859060402 
The precision is 0.989916436373207 
The recall is 0.9899328859060402 
The f1-score is 0.9898964449560658

In Percentage : 

The accuracy is 98.99 % 
The precision is 98.99 % 
The recall is 98.99 % 
The f1-score is 98.99 %


The accuracy is 98.99 % that means model is performing well on the test data. 
The precision is 98.99 % that means model is performing well on the test data.
The recall is 98.99 % that means model is performing well on the test data.
The f1-score is 98.99 % that means model is performing well on the test data.

## Experiment with TF-IDF parameters such as max_features, ngram_range, and min_df.

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instead of using the model_pipeline i am doing it manually to experiment with different parameters of TF-IDF vectorizer.

"""  
n_grams : (1, 2) means unigrams and bigrams , (1,1) means only unigrams , (2,2) means only bigrams and so on. , (1,3) means unigrams , bigrams and trigrams and so on.
"""

vectorizer = TfidfVectorizer(
    max_features=5000, ngram_range=(1, 3), min_df=5, stop_words="english"
)
vectorizer.fit(X_train)
vectorized_X_train = vectorizer.transform(X_train)
vectorized_X_test = vectorizer.transform(X_test)

In [67]:
from sklearn.naive_bayes import MultinomialNB

n_model = MultinomialNB()
n_model.fit(vectorized_X_train, y_train)
y_pred = n_model.predict(vectorized_X_test)
y_pred

array(['tech', 'entertainment', 'sport', 'politics', 'politics', 'tech',
       'entertainment', 'business', 'entertainment', 'entertainment',
       'business', 'politics', 'politics', 'sport', 'entertainment',
       'business', 'business', 'entertainment', 'business',
       'entertainment', 'tech', 'sport', 'tech', 'politics', 'tech',
       'sport', 'sport', 'entertainment', 'politics', 'entertainment',
       'business', 'entertainment', 'business', 'politics', 'tech',
       'business', 'politics', 'politics', 'sport', 'entertainment',
       'business', 'tech', 'sport', 'sport', 'business', 'tech', 'sport',
       'entertainment', 'tech', 'business', 'sport', 'entertainment',
       'sport', 'tech', 'tech', 'politics', 'business', 'politics',
       'business', 'sport', 'business', 'politics', 'sport', 'tech',
       'sport', 'tech', 'entertainment', 'politics', 'sport', 'politics',
       'entertainment', 'business', 'sport', 'tech', 'sport', 'politics',
       'politics', 'bu

In [68]:
# More predictions from the outer world data.

# 1. to train the model first we need to vectorize the data using TF-IDF vectorizer and then we can train the model using the vectorized data.
# 2. to test the model we need to vectorize the test data using the same TF-IDF vectorizer and then we can test the model using the vectorized test data.
# 3. to predict the new data we need to vectorize the new data using the same TF-IDF vectorizer

data = [
    "The stock market is experiencing a significant downturn due to global economic uncertainty.",
    "The local football team won the championship after a thrilling match.",
    "The government has announced new policies to address climate change and reduce carbon emissions.",
    "The latest smartphone model features advanced camera technology and improved battery life.",
    "The movie received rave reviews from critics and audiences alike, making it a box office hit .",
]

vectorized_data = vectorizer.transform(data)
n_model.predict(vectorized_data)

# data chai vectorized hunei parxa as model nei vectorized data ma train vako xa.

array(['business', 'sport', 'politics', 'tech', 'entertainment'],
      dtype='<U13')

## 3. Classify at least five custom news articles and record the predicted categories.

In [69]:
custom_news_articles = [
    "The stock market is experiencing a significant downturn due to global economic uncertainty.",
    "A new study reveals the potential health benefits of a plant-based diet.",
    "The local football team won the championship after a thrilling final match.",
    "Scientists have discovered a new exoplanet that may have conditions suitable for life.",
    "The government has announced new policies to combat climate change and reduce carbon emissions.",
]


vectorized_custom_news_articles = vectorizer.transform(custom_news_articles)
predicted_categories = n_model.predict(vectorized_custom_news_articles)
predicted_categories

array(['business', 'business', 'sport', 'entertainment', 'politics'],
      dtype='<U13')

## 4. Save the trained model and reload it to perform predictions on new data

In [70]:
joblib.dump(n_model , "../models/n_model.joblib")

['../models/n_model.joblib']

In [71]:
imported_n_model = joblib.load("../models/n_model.joblib")

new_data = [
    "I eat stock market and it is going down due to global economic uncertainty.",
    "I study alot but i am not able to get good grades in my exams and i am very sad about it.",
    "I fart and it smells like a rotten egg and i am very embarrassed about it.",
    "I am very happy today because i got a new job and i am very excited about it.",
    "I am very sad today because my dog died and i am very heartbroken about it.",
]

new_data_v = vectorizer.transform(new_data)
new_data_pred = imported_n_model.predict(new_data_v)
new_data_pred


# it didn't give good predictions because the new data is not related to the training data. The model was trained on news articles and the new data is not news articles. The model is not able to generalize well to new data that is not similar to the training data.

array(['business', 'tech', 'sport', 'sport', 'entertainment'],
      dtype='<U13')

## 5. Experiment with Train-Test Split Ratio and using different test sizes such as 0.1, 0.2, 0.3, and 0.4. Record the accuracy, precision, recall, and f1-score for each test size.

In [72]:
new_X = new_df["Text"]
new_y = new_df["Category"]

In [73]:
from sklearn.pipeline import make_pipeline

test_sizes = [0.1, 0.2, 0.3, 0.4]

results = []
for test_size in test_sizes:
    X_train, X_test, y_train, y_test = train_test_split(
        new_X, new_y, test_size=test_size, random_state=42
    )

    pipeline = make_pipeline(TfidfVectorizer(), MultinomialNB())
    model = pipeline.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(y_pred)

    accuracy = accuracy_score(y_test, y_pred)

    train_percent = int((1 - test_size) * 100)
    test_percent = int(test_size * 100)

    results.append(
        {
            "train_percent": train_percent,
            "test_percent": test_percent,
            "accuracy": accuracy,
        }
    )

['business' 'politics' 'politics' 'politics' 'sport' 'business' 'tech'
 'entertainment' 'business' 'tech' 'politics' 'entertainment' 'business'
 'sport' 'tech' 'politics' 'business' 'sport' 'politics' 'business' 'tech'
 'entertainment' 'sport' 'business' 'sport' 'tech' 'business' 'sport'
 'tech' 'business' 'sport' 'business' 'business' 'politics' 'sport' 'tech'
 'politics' 'business' 'entertainment' 'tech' 'sport' 'business'
 'politics' 'business' 'sport' 'business' 'politics' 'tech' 'politics'
 'business' 'sport' 'sport' 'business' 'sport' 'politics' 'entertainment'
 'entertainment' 'politics' 'business' 'entertainment' 'tech' 'business'
 'politics' 'tech' 'tech' 'tech' 'business' 'tech' 'politics' 'politics'
 'politics' 'sport' 'sport' 'sport' 'entertainment' 'entertainment'
 'business' 'politics' 'business' 'business' 'business' 'sport' 'sport'
 'sport' 'business' 'entertainment' 'sport' 'business' 'business' 'tech'
 'entertainment' 'business' 'politics' 'tech' 'business' 'politics'

In [74]:
print("Results for different train-test split ratios:")

for result in results:
    print(
        f"Train-Test Split: {result['train_percent']}% - {result['test_percent']}% | Accuracy: {result['accuracy']*100:.2f}%"
    )

Results for different train-test split ratios:
Train-Test Split: 90% - 10% | Accuracy: 95.30%
Train-Test Split: 80% - 20% | Accuracy: 95.30%
Train-Test Split: 70% - 30% | Accuracy: 95.75%
Train-Test Split: 60% - 40% | Accuracy: 93.29%


In conclusion , the accuracy of 70 | 30 split is the highest among all the tested ratios.

## Perform 5-Fold Cross Validation and calculate Mean Accuracy and Standard Deviation .

In [75]:
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline

"""
    Cross Validation : It is the technique used in ML in order to reduce overfitting , maximize use of data. It divides the data into multiple folds 
    and iteratively uses (majority of folds as training data and other folds as test data to measure performance metrics of a model.)

    It iterate taking multiple fold while shuffling it. 
"""


X = new_df['Text']
y = new_df['Category']


model = make_pipeline(TfidfVectorizer() , MultinomialNB())

scores = cross_val_score(model , X , y , cv=5 , scoring='accuracy')
print(scores)

mean_accuracy = np.mean(scores)
std_deviation = np.std(scores)

print(f"5 Cross Validation Result\n")
print(f"Mean accuracy is {mean_accuracy:.3f} and standard deviation is {std_deviation:.3f}")
print(f"Mean accuracy in percentage is {mean_accuracy*100:.3f} and standard deviation is {std_deviation*100:.3f}")
print(f"Model Reliability Range: {mean_accuracy - std_deviation:.4f} to {mean_accuracy + std_deviation:.4f}")

[0.94295302 0.9261745  0.94295302 0.97315436 0.95302013]
5 Cross Validation Result

Mean accuracy is 0.948 and standard deviation is 0.015
Mean accuracy in percentage is 94.765 and standard deviation is 1.539
Model Reliability Range: 0.9323 to 0.9630


Discussion of Model across different folds. 
[0.94295302 0.9261745  0.94295302 0.97315436 0.95302013]

- Fold 1 : Accuracy = 0.94295302 which is 94.29 %. 
- Fold 2 : Accuracy = 0.9261745 which is 92.61 %. 
- Fold 3 : Accuracy = 0.94295302 which is 94.29 %. 
- Fold 4 : Accuracy = 0.97315436 which is 97.31 %. 
- Fold 5 : Accuracy = 0.95302013 which is 95.30 %.  


The model is very stable across multiple folds as the SD of it is relatively small which is 1.539 % that shows the variance is very low and the model is performing well across multiple folds.

## Training and comparision table showing accuracy , training time , prediction time for models like Logistic Regression , SVM and multinomial Naive Bayes.

In [76]:
# training for logistic regression. we use multinomial logistic regression as we have nonordinal data.

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import time

In [77]:
X = new_df["Text"]
y = new_df["Category"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [78]:
# using support vector machines : it basically draws the line between the two different classes and separates them with the margin.
from sklearn.svm import SVC

vectorizer_svm = TfidfVectorizer(
    max_features=5000, ngram_range=(1, 3), min_df=5, stop_words="english"
)
vectorizer_svm.fit(X_train)
vectorized_X_train_svm = vectorizer_svm.transform(X_train)
vectorized_X_test_svm = vectorizer_svm.transform(X_test)

# creating an svm classifier

svm_classifier = SVC(kernel="linear", C=1.0)

# training the model
st_svm = time.perf_counter()
svm_classifier.fit(vectorized_X_train_svm, y_train)
et_svm = time.perf_counter()

tt_svm = et_svm - st_svm
print(f"The training time is {tt_svm} seconds ")

st_svm_pred = time.perf_counter()
y_pred_svm = svm_classifier.predict(vectorized_X_test_svm)
et_svm_pred = time.perf_counter()

pred_time_svm = et_svm_pred - st_svm_pred
accuracy_svm = accuracy_score(y_test, y_pred_svm) * 100

print(f"The total prediction time is {pred_time_svm:.4f} seconds")
print(f"Accuracy is {accuracy_svm:.3f} %")

The training time is 2.319694044001153 seconds 
The total prediction time is 0.3622 seconds
Accuracy is 97.315 %


In [79]:
# Multinomial naive bayes

st_time_nb_nb = time.perf_counter()

pipeline = make_pipeline(TfidfVectorizer(), MultinomialNB())
pipeline.fit(X_train, y_train)
et_time_nb_train = time.perf_counter()

st_time_nb_nb_test = time.perf_counter()

y_pred_nb = pipeline.predict(X_test)
et_time_nb_test = time.perf_counter()

pred_time_nb = et_time_nb_test - st_time_nb_nb_test
train_time_nb = et_time_nb_train - st_time_nb_nb
accuracy_naive = accuracy_score(y_test , y_pred_nb)*100

print(f"Training time : {train_time_nb} seconds \nPrediction Time: {pred_time_nb} seconds.\n")
print(f"Accuracy is {accuracy_naive:.3f} %")

Training time : 0.31365924599958817 seconds 
Prediction Time: 0.06144437100010691 seconds.

Accuracy is 95.302 %


In [80]:
st_time_log_train = time.perf_counter()

vectorizer = TfidfVectorizer(
    max_features=5000, ngram_range=(1, 3), min_df=5, stop_words="english"
)

vectorizer.fit(X_train)
vectorized_X_train = vectorizer.transform(X_train)
vectorized_X_test = vectorizer.transform(X_test)

reg_model = LogisticRegression(max_iter=10000, random_state=0)
reg_model.fit(vectorized_X_train, y_train)

et_time_log_train = time.perf_counter()

st_time_log_test = time.perf_counter()

y_pred = reg_model.predict(vectorized_X_test)

et_time_log_test = time.perf_counter()

train_time_log = et_time_log_train - st_time_log_train
pred_time_log = et_time_log_test - st_time_log_test
accuracy_logistic = accuracy_score(y_test , y_pred)*100
print(f"Training Time : {train_time_log} seconds")
print(f"Prediction Time : {pred_time_log} seconds")
print(f"Accuracy is {accuracy_logistic:.3f} %")

Training Time : 6.031768310000189 seconds
Prediction Time : 0.0013704369994229637 seconds
Accuracy is 96.644 %


In [81]:
# Table creation or dataframe creation comparing all the comparision of svm, logistic regression and multinomial naive bayes

comparision_ac_tt_pt = pd.DataFrame(
    {
        "Accuracy": [accuracy_logistic, accuracy_svm, accuracy_naive],
        "Training Time": [train_time_log, tt_svm, train_time_nb],
        "Prediction Time": [pred_time_log, pred_time_svm, pred_time_nb],
    },
    index=["Logistic", "SVM", "Multinomial"],
)
comparision_ac_tt_pt

,Accuracy,Training Time,Prediction Time
Logistic,96.644295,6.031768,0.001370
SVM,97.315436,2.319694,0.362172
Multinomial,95.302013,0.313659,0.061444
